# SPDX-FileCopyrightText: 2023 - 2024 Daniel Wolf <nephatrine@gmail.com>
#
# SPDX-License-Identifier: ISC

name: Build Container Image
run-name: ${{ gitea.actor }} pushed to ${{ gitea.repository }}:${{ gitea.ref_name }}
on:
  push:
  schedule:
    - cron:  '0 19 * * 3'
jobs:
  build_amd64:
    if: gitea.repository_owner == 'NephNET' && (!(startsWith(gitea.event.head_commit.message, 'chore') || startsWith(gitea.event.head_commit.message, 'docs')) || gitea.event_name == 'schedule')
    runs-on: nephnet-amd64
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: https://github.com/actions/checkout@v4
      - name: BuildX Setup
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Build & Push (Master)
        uses: https://github.com/docker/build-push-action@v5
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          context: .
          platforms: linux/amd64
          provenance: false
          pull: true
          push: true
          file: Dockerfile
          tags: code.nephatrine.net/nephnet/amd64:remark42-ce
          cache-from: type=registry,ref=code.nephatrine.net/nephnet/amd64-cache:remark42-ce
          cache-to: type=registry,image-manifest=true,oci-mediatypes=true,ref=code.nephatrine.net/nephnet/amd64-cache:remark42-ce,mode=max
      - name: Build & Push (Branch)
        if: gitea.ref_name != 'master' && gitea.ref_name != ''
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-unknown}
          docker buildx build --pull -t code.nephatrine.net/nephnet/remark42-ce:${BRANCH}-amd64 --platform linux/amd64 -f Dockerfile ${{ gitea.workspace }}
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure() || gitea.event_name != 'schedule'
        with:
          title: "Container Build (X86_64; 1.12.1)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  push_amd64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_amd64]
    runs-on: nephnet-amd64
    continue-on-error: true
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Tag & Push
        run: |
          docker pull code.nephatrine.net/nephnet/amd64:remark42-ce --platform linux/amd64
          docker tag code.nephatrine.net/nephnet/amd64:remark42-ce nephatrine/amd64:remark42-ce
          docker rmi code.nephatrine.net/nephnet/amd64:remark42-ce
          docker push nephatrine/amd64:remark42-ce
          docker rmi nephatrine/amd64:remark42-ce
  build_i386:
    if: gitea.repository_owner == 'NephNET' && (!(startsWith(gitea.event.head_commit.message, 'chore') || startsWith(gitea.event.head_commit.message, 'docs')) || gitea.event_name == 'schedule')
    runs-on: nephnet-i386
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: https://github.com/actions/checkout@v4
      - name: BuildX Setup
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Build & Push (Master)
        uses: https://github.com/docker/build-push-action@v5
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          context: .
          platforms: linux/386
          provenance: false
          pull: true
          push: true
          file: Dockerfile
          tags: code.nephatrine.net/nephnet/i386:remark42-ce
          cache-from: type=registry,ref=code.nephatrine.net/nephnet/i386-cache:remark42-ce
          cache-to: type=registry,image-manifest=true,oci-mediatypes=true,ref=code.nephatrine.net/nephnet/i386-cache:remark42-ce,mode=max
      - name: Build & Push (Branch)
        if: gitea.ref_name != 'master' && gitea.ref_name != ''
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-unknown}
          docker buildx build --pull -t code.nephatrine.net/nephnet/remark42-ce:${BRANCH}-i386 --platform linux/386 -f Dockerfile ${{ gitea.workspace }}
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Build (I686; 1.12.1)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  push_i386:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_i386]
    runs-on: nephnet-amd64
    continue-on-error: true
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Tag & Push
        run: |
          docker pull code.nephatrine.net/nephnet/i386:remark42-ce --platform linux/386
          docker tag code.nephatrine.net/nephnet/i386:remark42-ce nephatrine/ia32:remark42-ce
          docker rmi code.nephatrine.net/nephnet/i386:remark42-ce
          docker push nephatrine/ia32:remark42-ce
          docker rmi nephatrine/ia32:remark42-ce
  build_arm64:
    if: gitea.repository_owner == 'NephNET' && (!(startsWith(gitea.event.head_commit.message, 'chore') || startsWith(gitea.event.head_commit.message, 'docs')) || gitea.event_name == 'schedule')
    runs-on: nephnet-arm64
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: https://github.com/actions/checkout@v4
      - name: BuildX Setup
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Build & Push (Master)
        uses: https://github.com/docker/build-push-action@v5
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          context: .
          platforms: linux/arm64/v8
          provenance: false
          pull: true
          push: true
          file: Dockerfile
          tags: code.nephatrine.net/nephnet/arm64:remark42-ce
          cache-from: type=registry,ref=code.nephatrine.net/nephnet/arm64-cache:remark42-ce
          cache-to: type=registry,image-manifest=true,oci-mediatypes=true,ref=code.nephatrine.net/nephnet/arm64-cache:remark42-ce,mode=max
      - name: Build & Push (Branch)
        if: gitea.ref_name != 'master' && gitea.ref_name != ''
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-unknown}
          docker buildx build --pull -t code.nephatrine.net/nephnet/remark42-ce:${BRANCH}-arm64 --platform linux/arm64/v8 -f Dockerfile ${{ gitea.workspace }}
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Build (AARCH64; 1.12.1)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  push_arm64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_arm64]
    runs-on: nephnet-amd64
    continue-on-error: true
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Tag & Push
        run: |
          docker pull code.nephatrine.net/nephnet/arm64:remark42-ce --platform linux/arm64/v8
          docker tag code.nephatrine.net/nephnet/arm64:remark42-ce nephatrine/arm64:remark42-ce
          docker rmi code.nephatrine.net/nephnet/arm64:remark42-ce
          docker push nephatrine/arm64:remark42-ce
          docker rmi nephatrine/arm64:remark42-ce
  build_armhf:
    if: gitea.repository_owner == 'NephNET' && (!(startsWith(gitea.event.head_commit.message, 'chore') || startsWith(gitea.event.head_commit.message, 'docs')) || gitea.event_name == 'schedule')
    runs-on: nephnet-armhf
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: https://github.com/actions/checkout@v4
      - name: BuildX Setup
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Build & Push (Master)
        uses: https://github.com/docker/build-push-action@v5
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          context: .
          platforms: linux/arm/v7
          provenance: false
          pull: true
          push: true
          file: Dockerfile
          tags: code.nephatrine.net/nephnet/armv7:remark42-ce
          cache-from: type=registry,ref=code.nephatrine.net/nephnet/armv7-cache:remark42-ce
          cache-to: type=registry,image-manifest=true,oci-mediatypes=true,ref=code.nephatrine.net/nephnet/armv7-cache:remark42-ce,mode=max
      - name: Build & Push (Branch)
        if: gitea.ref_name != 'master' && gitea.ref_name != ''
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-unknown}
          docker buildx build --pull -t code.nephatrine.net/nephnet/remark42-ce:${BRANCH}-armv7 --platform linux/arm/v7 -f Dockerfile ${{ gitea.workspace }}
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Build (ARMV7L; 1.12.1)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  push_armhf:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_armhf]
    runs-on: nephnet-amd64
    continue-on-error: true
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Tag & Push
        run: |
          docker pull code.nephatrine.net/nephnet/armv7:remark42-ce --platform linux/arm/v7
          docker tag code.nephatrine.net/nephnet/armv7:remark42-ce nephatrine/armv7:remark42-ce
          docker rmi code.nephatrine.net/nephnet/armv7:remark42-ce
          docker push nephatrine/armv7:remark42-ce
          docker rmi nephatrine/armv7:remark42-ce
  build:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_amd64, build_i386, build_arm64, build_armhf]
    runs-on: nephnet
    continue-on-error: true
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Manifest
        run: |
          docker manifest create code.nephatrine.net/nephnet/remark42-ce:1.12.1 --amend code.nephatrine.net/nephnet/amd64:remark42-ce --amend code.nephatrine.net/nephnet/i386:remark42-ce --amend code.nephatrine.net/nephnet/arm64:remark42-ce --amend code.nephatrine.net/nephnet/armv7:remark42-ce
          docker manifest create code.nephatrine.net/nephnet/remark42-ce:1.12 --amend code.nephatrine.net/nephnet/amd64:remark42-ce --amend code.nephatrine.net/nephnet/i386:remark42-ce --amend code.nephatrine.net/nephnet/arm64:remark42-ce --amend code.nephatrine.net/nephnet/armv7:remark42-ce
          docker manifest create code.nephatrine.net/nephnet/remark42-ce:1 --amend code.nephatrine.net/nephnet/amd64:remark42-ce --amend code.nephatrine.net/nephnet/i386:remark42-ce --amend code.nephatrine.net/nephnet/arm64:remark42-ce --amend code.nephatrine.net/nephnet/armv7:remark42-ce
          docker manifest create code.nephatrine.net/nephnet/remark42-ce:latest --amend code.nephatrine.net/nephnet/amd64:remark42-ce --amend code.nephatrine.net/nephnet/i386:remark42-ce --amend code.nephatrine.net/nephnet/arm64:remark42-ce --amend code.nephatrine.net/nephnet/armv7:remark42-ce
          docker manifest push --purge code.nephatrine.net/nephnet/remark42-ce:1.12.1
          docker manifest push --purge code.nephatrine.net/nephnet/remark42-ce:1.12
          docker manifest push --purge code.nephatrine.net/nephnet/remark42-ce:1
          docker manifest push --purge code.nephatrine.net/nephnet/remark42-ce:latest
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Publish (1.12.1)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_PACKAGE }}
  push:
    needs: [push_amd64, push_i386, push_arm64, push_armhf]
    runs-on: nephnet
    continue-on-error: true
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Manifest
        run: |
          docker manifest create nephatrine/remark42-ce:1.12.1 --amend nephatrine/amd64:remark42-ce --amend nephatrine/ia32:remark42-ce --amend nephatrine/arm64:remark42-ce --amend nephatrine/armv7:remark42-ce
          docker manifest create nephatrine/remark42-ce:1.12 --amend nephatrine/amd64:remark42-ce --amend nephatrine/ia32:remark42-ce --amend nephatrine/arm64:remark42-ce --amend nephatrine/armv7:remark42-ce
          docker manifest create nephatrine/remark42-ce:1 --amend nephatrine/amd64:remark42-ce --amend nephatrine/ia32:remark42-ce --amend nephatrine/arm64:remark42-ce --amend nephatrine/armv7:remark42-ce
          docker manifest create nephatrine/remark42-ce:latest --amend nephatrine/amd64:remark42-ce --amend nephatrine/ia32:remark42-ce --amend nephatrine/arm64:remark42-ce --amend nephatrine/armv7:remark42-ce
          docker manifest push --purge nephatrine/remark42-ce:1.12.1
          docker manifest push --purge nephatrine/remark42-ce:1.12
          docker manifest push --purge nephatrine/remark42-ce:1
          docker manifest push --purge nephatrine/remark42-ce:latest
      - name: Notify Discord
        if: gitea.event_name != 'schedule'
        uses: https://github.com/sarisia/actions-status-discord@v1
        with:
          title: "DockerHub: remark42-ce (1.12.1)"
          description: "The container image was pushed to [DockerHub](https://hub.docker.com/repository/docker/nephatrine/remark42-ce/general).\nPull `nephatrine/remark42-ce:latest` for the newest image."
          nodetail: true
          webhook: ${{ secrets.DISCORD_WEBHOOK_PACKAGE }}
  update_readme:
    needs: [push]
    runs-on: nephnet
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: https://github.com/actions/checkout@v4
      - name: Docker Describe
        uses: https://github.com/peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: nephatrine/remark42-ce
